#!/bin/sh
#Author Dian F

INTERFACE="wlan0"
Network=$( iwconfig $INTERFACE | egrep -o \"[A-Za-z1-9_]+\" 2>&1 )
URL="http://172.16.0.12/CP/sq.html"

if [[ "$Network" = "\"VALA_Free\"" ]]
then
ONLINE=$( curl "http://detectportal.firefox.com/" )
  if [[ "$ONLINE" != "success" ]]
  then
    timeout 4s /usr/bin/xterm -class "wifiLogin" -e "elinks -eval \"set document.browse.forms.confirm_submit=0\" -auto-submit 1 $URL"
    #I set the class attr in xterm so I can ref it in i3 to hide it from the current workspace
    connectToVala "tried"
  else
    #if you have i3 install then it will show you a notification the the connection was successfull
    if  [[ "$1" == "tried" ]]
    then
      timeout 2s i3-nagbar -m "Succesfully Connected to Internet"
      return 0
    fi
  fi
fi
